version: '3.4'

services:
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
  
  orderapi:
    image: ${DOCKER_REGISTRY-}orderapi
    container_name: "orderapi"
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    depends_on:
      - db

  productapi:
    image: ${DOCKER_REGISTRY-}productapi
    container_name: "productapi"
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
    depends_on:
      - db
    
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "sendeo-db"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Sendeo123."
        ACCEPT_EULA: "Y"
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672

