version: '3.4'

services:
  orderservice.api:
    image: ${DOCKER_REGISTRY-}orderserviceapi
    build:
      context: .
      dockerfile: OrderService.API/Dockerfile
    depends_on:
      - db
    ports:
      - "5000:80"
      - "5001:443"
  productservice.api:
    image: ${DOCKER_REGISTRY-}productserviceapi
    build:
      context: .
      dockerfile: ProductService.API/Dockerfile
    depends_on:
      - db
    ports:
      - "6000:80"
      - "6001:443"
  apigateway:
    image: ${DOCKER_REGISTRY-}apigateway
    build:
      context: .
      dockerfile: ApiGateway/Dockerfile
    ports:
      - "8000:80"
      - "8001:443"
  db:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: "sendeo-db"
    ports:
        - "1433:1433"
    environment:
        SA_PASSWORD: "Sendeo123."
        ACCEPT_EULA: "Y"
 
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
        - 5672:5672
        - 15672:15672
