// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductAPI.Data;

#nullable disable

namespace ProdcutAPI.Migrations
{
    [DbContext(typeof(ProdcutAPIContext))]
    [Migration("20221210224507_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ProdcutAPI.Entities.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageFile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = "fe9caa14-3e26-4e29-8a81-96b7bddda6ea",
                            Category = "Category1",
                            Description = "Description1",
                            ImageFile = "ImageFile1",
                            Name = "Name1",
                            Price = 100m,
                            Stock = 0
                        },
                        new
                        {
                            Id = "2e36494f-2baa-4e32-857d-f825264fb97a",
                            Category = "Category2",
                            Description = "Description2",
                            ImageFile = "ImageFile1",
                            Name = "Name1",
                            Price = 100m,
                            Stock = 0
                        },
                        new
                        {
                            Id = "440c6650-cfba-4a2d-9e86-14e0fcafd3db",
                            Category = "Category1",
                            Description = "Description3",
                            ImageFile = "ImageFile1",
                            Name = "Name1",
                            Price = 200m,
                            Stock = 0
                        },
                        new
                        {
                            Id = "155a117a-8702-457b-af80-b739f4f6238c",
                            Category = "Category2",
                            Description = "Description4",
                            ImageFile = "ImageFile1",
                            Name = "Name1",
                            Price = 10m,
                            Stock = 0
                        },
                        new
                        {
                            Id = "b529d950-af8b-4f11-9fc5-4cd5c4b3ad91",
                            Category = "Category3",
                            Description = "Description5",
                            ImageFile = "ImageFile1",
                            Name = "Name1",
                            Price = 250m,
                            Stock = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
